---

- name: Set correct directory ownership
  file:
    dest: "{{ item }}"
    owner: www-data
    group: www-data
    recurse: true
  with_items:
   - /var/www/html/craftible/storage
   - /var/www/html/craftible/config
   - /var/www/html/craftible/web

- name: Create .env
  template:
    src: .env.j2
    dest: "/var/www/html/{{ project_name }}/.env"
    owner: root
    group: root
    mode: 0644
  when: config_flavor == "provision"

- name: Generate application and security keys
  ansible.builtin.command: php /var/www/html/{{ project_name }}/craft setup/keys
  when: config_flavor == "provision"
 
- name: Craft Up
  ansible.builtin.command: php /var/www/html/{{ project_name }}/craft up
  when: config_flavor == "deploy"

- name: Craft Clear Caches
  ansible.builtin.command: php /var/www/html/{{ project_name }}/craft clear-caches/all
  when: config_flavor == "deploy"