---

# https://stackoverflow.com/questions/73724567/how-to-have-multiple-tasks-under-one-role-in-ansible

- name: Set correct directory ownership
  file:
    dest: "{{ item }}"
    owner: www-data
    group: www-data
    recurse: true
  with_items:
   - /var/www/html/craftible/storage
   - /var/www/html/craftible/config
   - /var/www/html/craftible/web
  when: config_flavor == "provision"

- name: Create .env
  template:
    src: .env.j2
    dest: "/var/www/html/{{ project_name }}/.env"
    owner: root
    group: root
    mode: 0644
  when: config_flavor == "provision"

- name: Generate application and security keys
  command: php /var/www/html/{{ project_name }}/craft setup/keys
  when: config_flavor == "provision"