---

- name: Install Apache2
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apache2

- name: Enable UFW Firewall
  ufw:
    rule: allow
    name: "{{ item }}"
    direction: in
    state: enabled
  with_items:
    - OpenSSH
    - Apache Full
    # TODO - Change this to "Apache Secure" once playbook is done

- name: Create project directory
  file:
    path: "/var/www/html/{{ project_name }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Disable default Apache virtualhost
  command: >
    a2dissite 000-default
    removes=/etc/apache2/sites-enabled/000-default.conf

- name: Remove default Apache Config
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/sites-available/000-default.conf
    - /etc/apache2/sites-available/default-ssl.conf
    - /var/www/html/index.html

- name: Add domain specific Apache Config
  template:
    src: virtual_host.conf.j2
    dest: "/etc/apache2/sites-available/{{ project_domain }}.conf"
    owner: root
    group: root
    mode: 0644

- name: Enable CraftCMS Site
  command: >
    a2ensite {{ project_domain }}
    creates=/etc/apache2/sites-enabled/{{ project_domain }}.conf

- name: Enable Apache rewrite module (required for Craft CMS).
  apache2_module:
    name: rewrite
    state: present

- name: Restart Apache service
  service:
    name: apache2
    state: restarted