---

- name: Install MySQL packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - mysql-server
    - python3-pip

- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present

- name: Create Database User "craft" for CMS
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create project database
  community.mysql.mysql_db:
    name: "{{ project_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock