---

- name: Add latest php apt repository into sources list
  apt_repository:
      repo: ppa:ondrej/php
      state: present
      update_cache: true

- name: Install PHP and Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - php8.3-fpm
    - libapache2-mod-php8.3
    - php8.3-mysql
    - php8.3-bcmath
    - php8.3-curl
    - php8.3-zip
    - php8.3-dom
    - php8.3-simplexml
    - php8.3-mbstring
    - php8.3-gd
    - php8.3-intl
    - php8.3-soap
    - php8.3-opcache

- name: Update FPM php.ini
  template:
    src: php.ini.j2
    dest: /etc/php/8.3/fpm/php.ini
    backup: yes
    owner: root
    group: root
    mode: 0644

- name: Update CLI php.ini
  template:
    src: php.ini.j2
    dest: /etc/php/8.3/cli/php.ini
    backup: yes
    owner: root
    group: root
    mode: 0644

# Not sure if needed atm
- name: Disable older versions of PHP for Apache
  community.general.apache2_module:
    state: absent
    name: "{{ item }}"
  with_items:
    - php7.0
    - php7.1
    - php7.2
    - php7.3
    - php7.4
    - php8.0
    - php8.1
    - php8.2
    - php8.3
    - php8.4
    - mpm_prefork

- name: Enable PHP8.3 Event Apache Module
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - mpm_event
    - proxy_fcgi
    - http2

- name: Enabling PHP8.3-FPM Conf
  command: >
    a2enconf php8.3-fpm

- name: Restart Apache service
  service:
    name: apache2
    state: restarted