---
- name: Provision server
  hosts: all
  remote_user: root

  tasks:
  - name: Install APT packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
     - apache2
     - mysql-server
     - python3-pip
  
  - name: Enable UFW Firewall
    ufw:
      rule: allow
      name: "{{ item }}"
      direction: in
      state: enabled
    with_items:
      - OpenSSH
      - Apache Full
      # TODO - Change this to "Apache Secure" once playbook is done

  - name: Make sure pymysql is present
    pip:
      name: pymysql
      state: present

  - name: Create Database User "craft" for CMS
    mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"
      priv: '*.*:ALL'
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
    