---
- name: Provision server
  hosts: all
  remote_user: root

  tasks:
  - name: Generate /root/.ssh/ RSA host key
    openssh_keypair:
      path: /root/.ssh/id_rsa
      owner: root
      group: root

  - name: Fix owner of the generated pub key
    file:
      path: /root/.ssh/id_rsa.pub
      owner: root
      group: root

  roles:
    - apache
    - php
    - mysql