---
- name: Provision server
  hosts: all
  remote_user: root

  vars:
    certbot_install_method: snap
    certbot_auto_renew_user: admin@craftible.co.uk
    certbot_auto_renew_minute: "20"
    certbot_auto_renew_hour: "5"

  tasks:
  - name: Generate /root/.ssh/ RSA host key
    openssh_keypair:
      path: /root/.ssh/id_rsa
      owner: root
      group: root

  - name: Fix owner of the generated pub key
    file:
      path: /root/.ssh/id_rsa.pub
      owner: root
      group: root

  roles:
    - apache
    - php
    - mysql
    # - geerlingguy.certbot
    - composer
    - craftcms
      config_flavor: provision