---

- name: Install Composer
  ansible.builtin.apt:
    name: composer
    state: present
    update_cache: true

- name: Composer install php packages
  community.general.composer:
    command: install
    working_dir: "/var/www/html/{{ project_name }}"
    no_dev: false
    no_scripts: yes
    no_plugins: yes
    optimize_autoloader: yes
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"